/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.pdreditors;

import java.awt.Component;
import java.io.IOException;
import javax.persistence.EntityManager;
import org.netbeans.spi.actions.AbstractSavable;
import org.openide.util.Lookup;
import org.openide.util.LookupEvent;
import org.openide.util.LookupListener;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Employees;

import systems.tech247.hr.Nationalities;
import systems.tech247.hr.Tribes;
import systems.tech247.pdr.Utility;
import systems.tech247.util.Gender;

/**
 *
 * @author Admin
 */
public final class EmpProbationPanel extends javax.swing.JPanel implements LookupListener{

    Employees emp;
    DataAccess da = new DataAccess();
    Tribes tribeID;
    Nationalities nationalityID;
    short genderID;
    EntityManager entityManager = da.getEntityManager();
    TopComponent empTc = WindowManager.getDefault().findTopComponent("EmployeesTopComponent");
    Lookup.Result<Employees> empRslt = empTc.getLookup().lookupResult(Employees.class);
    
    /**
     * Creates new form PersonalInfoPanel
     */
    public EmpProbationPanel() {
        initComponents();
        //Start transaction
        
        empRslt.addLookupListener(this);
        resultChanged(new LookupEvent(empRslt));
       disableInput();
       
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jDProbationStart = new com.toedter.calendar.JDateChooser();
        jcbOnProbation = new javax.swing.JCheckBox();
        jtProbationPeriod = new javax.swing.JTextField();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(EmpProbationPanel.class, "EmpProbationPanel.jLabel2.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(EmpProbationPanel.class, "EmpProbationPanel.jLabel3.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jcbOnProbation, org.openide.util.NbBundle.getMessage(EmpProbationPanel.class, "EmpProbationPanel.jcbOnProbation.text")); // NOI18N

        jtProbationPeriod.setText(org.openide.util.NbBundle.getMessage(EmpProbationPanel.class, "EmpProbationPanel.jtProbationPeriod.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jcbOnProbation)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jDProbationStart, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                        .addComponent(jtProbationPeriod)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jcbOnProbation)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel2)
                    .addComponent(jtProbationPeriod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jLabel3)
                    .addComponent(jDProbationStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(359, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser jDProbationStart;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JCheckBox jcbOnProbation;
    private javax.swing.JTextField jtProbationPeriod;
    // End of variables declaration//GEN-END:variables

    @Override
    public void resultChanged(LookupEvent le) {
        Lookup.Result result = (Lookup.Result)le.getSource();
        for (Object e: result.allInstances()){
            if(e instanceof Employees){
                
                emp = (Employees)e;
                
                disableInput();
                
                try{
                if(((Employees) e).getIsOnProbation()){
                    jcbOnProbation.setSelected(true);
                    jDProbationStart.setDate(((Employees) e).getProbationStartDate());
                   jtProbationPeriod.setText(((Employees) e).getProbationPeriod()+"");
                    
                }}catch(NullPointerException ex){
                    
                }
                
                
                try{
                               
                jDProbationStart.setDate(((Employees) e).getProbationStartDate());
                }catch(NullPointerException ex){
                    // When some info is missing
                }
                
                try{
                               
                jtProbationPeriod.setText(((Employees) e).getProbationPeriod()+"");
                }catch(NullPointerException ex){
                    // When some info is missing
                }
                
                
                
                
                
               
                
                
                
            }
            
            
            
            if(e instanceof Nationalities){
                nationalityID = (Nationalities)e;
                
                modify();
            }
            
            if(e instanceof Gender){
                genderID = ((Gender) e).getCode();
                
                modify();
            }
        }
    }
    
    void disableInput(){
        boolean shl = null != emp;
        Component[] comps = getComponents();
        for(Component c: comps){
            c.setEnabled(shl);
        }
    }
    
    void modify(){
        if(getLookup().lookup(MySavable.class)==null){
            Utility.editorIC.add(new MySavable());
        }
    }

    
    public Lookup getLookup() {
        TopComponent tc = WindowManager.getDefault().findTopComponent("EmployeeEditorTopComponent");
        return tc.getLookup();
    }
    
    private class MySavable extends AbstractSavable{

        public MySavable(){
            register();
        } 
        
        @Override
        protected String findDisplayName() {
            return "Employee";
        }

        @Override
        protected void handleSave() throws IOException {
                     
        }
        
        EmpProbationPanel pnel(){
            return EmpProbationPanel.this;
        }

        @Override
        public boolean equals(Object o) {
            if(o instanceof MySavable){
                MySavable m = (MySavable)o;
                return pnel() == m.pnel();
            }
            return false;
        }

        @Override
        public int hashCode() {
            return pnel().hashCode();
        }
        
    }
    
    
    
    
}
