/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package systems.tech247.pdreditors;

import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.persistence.EntityManager;
import javax.persistence.Query;
import org.openide.awt.StatusDisplayer;
import org.openide.util.Lookup;
import org.openide.windows.TopComponent;
import org.openide.windows.WindowManager;
import systems.tech247.dbaccess.DataAccess;
import systems.tech247.hr.Banks;
import systems.tech247.pdr.QueryBanks;
import systems.tech247.pdr.Utility;


/**
 *
 * @author Admin
 */
public class PDRBankEditor extends javax.swing.JPanel{

    
    
    DataAccess da = new DataAccess();
    Banks bank;
    
    
    
    
    //Updatables
  
    String bankString = null;
    String bankCode = null;
    String bankComments = null;
  
    EntityManager entityManager = da.getEntityManager();
    
   
    /**
     * Creates new form PersonalInfoPanel
     */
    public PDRBankEditor(){
        this(null);
    }
    
    
    
    
 public PDRBankEditor(Banks bank) {
        initComponents();
        //Start transaction
        
        jbSave.setEnabled(false);
        this.bank = bank;
        
        if(bank != null){
            jtBankName.setText(bank.getBankName());
            jtBankCode.setText(bank.getBankCode());
            jTBankComments.setText(bank.getComments());
            
        }
        
        
        jtBankName.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                bankString = jtBankName.getText();
                modify();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                bankString = jtBankName.getText(); 
                modify();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                bankString = jtBankName.getText();
                modify();
            }
        });
        
        jtBankCode.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                bankCode = jtBankCode.getText();
                modify();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                bankCode = jtBankCode.getText();  
                modify();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                bankCode = jtBankCode.getText();
                modify();
            }
        });
        
        jTBankComments.addKeyListener(new KeyListener() {
            @Override
            public void keyTyped(KeyEvent e) {
                bankComments = jTBankComments.getText();
                modify();
            }

            @Override
            public void keyPressed(KeyEvent e) {
                bankComments = jTBankComments.getText();   
                modify();
            }

            @Override
            public void keyReleased(KeyEvent e) {
                bankComments = jTBankComments.getText();
                modify();
            }
        });
        
        
        
        
        
        
        
        
        
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jtBankName = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtBankCode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTBankComments = new javax.swing.JTextArea();
        jbSave = new javax.swing.JButton();

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jLabel1.text")); // NOI18N

        jtBankName.setText(org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jtBankName.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jLabel2.text")); // NOI18N

        jtBankCode.setText(org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jtBankCode.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jLabel3.text")); // NOI18N

        jTBankComments.setColumns(20);
        jTBankComments.setRows(5);
        jScrollPane1.setViewportView(jTBankComments);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(jtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtBankName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtBankCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                .addContainerGap())
        );

        org.openide.awt.Mnemonics.setLocalizedText(jbSave, org.openide.util.NbBundle.getMessage(PDRBankEditor.class, "PDRBankEditor.jbSave.text")); // NOI18N
        jbSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbSave, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSave)
                .addGap(8, 8, 8))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jbSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSaveActionPerformed
        entityManager.getTransaction().begin();    
        
        if(bank == null){ //Add New Account
            String insertSQL = "INSERT INTO [dbo].[Banks]\n" +
"           ([BankCode]\n" +
"           ,[BankName]\n" +
"           ,[Comments])\n" +
"     VALUES\n" +
"           (?,?,?)";
            Query query = entityManager.createNativeQuery(insertSQL);
            query.setParameter(1, bankCode);
            query.setParameter(2, bankString);
            query.setParameter(3, bankComments);
            
            
            
            query.executeUpdate();
            entityManager.getTransaction().commit(); 
            
            
            resetEditor();
            
            StatusDisplayer.getDefault().setStatusText("Bank Saved");
                        
            String sqlString = "SELECT r from Banks r WHERE r.bankName LIKE '%"+bankString+"%'";
            Utility.loadBanks(sqlString);
        }else{
            
            Banks eba = entityManager.find(Banks.class, bank.getBankID());
            
            if(bankString != null){
                eba.setBankName(bankString);
            }
            if(bankCode != null){
                eba.setBankCode(bankCode);
            }
            if(bankComments != null){
                eba.setComments(bankComments);
            }
            
           
            
            
            
            entityManager.getTransaction().commit();
            StatusDisplayer.getDefault().setStatusText("Bank Saved");
            resetEditor();
            String sqlString = "SELECT r from Banks r WHERE r.bankName LIKE '%"+bankString+"%'";
            Utility.loadBanks(sqlString);
        }
        

    }//GEN-LAST:event_jbSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTBankComments;
    private javax.swing.JButton jbSave;
    private javax.swing.JTextField jtBankCode;
    private javax.swing.JTextField jtBankName;
    // End of variables declaration//GEN-END:variables

    
    
    
    void modify(){
        
                jbSave.setEnabled(true);
            
        
    }

    
    public Lookup getLookup() {
        TopComponent tc = WindowManager.getDefault().findTopComponent("EmployeeEditorTopComponent");
        return tc.getLookup();
    }
    
    
    
    void resetEditor(){
        jtBankName.setText("");
        bankString = null;
      
        
    }
    
    


}
